CursoIOT/Models/Luz.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CursoIOT.Models
{
    public class Luz
    {
        public int id { get; set; }
        public string nome { get; set; }
        public bool luz { get; set; }
        public bool status { get; set; }
    }
}

CursoIOT/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CursoIOT.Models
{
    public class Usuario
    {
        public int UsuarioId { get; set; }
        public string Nome { get; set; }
        public string senha { get; set; }
        public string Permissoes { get; set; }

    }
}

CursoIOT/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CursoIOT.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CursoIOT/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CursoIOT.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            if(ViewBag.nome == "Nicolas" && ViewBag.senha == "senha1")
            {

            }
                         
            return View();
        }
    }
}

CursoIOT/Controllers/LuzController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CursoIOT.Controllers
{
    public class LuzController : Controller
    {
        // GET: Luz
        public ActionResult Index()
        {
            return View();
        }
    }
}

CursoIOT/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CursoIOT.Controllers
{
    public class ProjectController : Controller
    {
        // GET: Project
        public ActionResult Index()
        {
            return View();
        }
    }
}

CursoIOT/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CursoIOT/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CursoIOT/Views/Home/Index.cshtml
<div class="container col-10">
    <div>
        <br />
        <h1 style="position:center">Ω Omega A Casa Inteligente</h1>
        <br />
    </div>
    <p style="position:center">
        Omega é um projeto para resolver seus problemas com tempo. ele resolve seus problemas antes mesmo de vc ficar sabendo. ele automaticamente indentifica o
        problema, procura as pessoas proximas e com melhor preço. assim que ele fizer essa analise, ele manda uma mensagem avisando qual o problema aconteceu e se voce
        quer agendar um horario para solucionar.
        <br />
        <button type="button" class="btn btn-primary" style="background-color:gray">Ler Mais</button>
    </p>

    <br />
    <br />
    <br />
    <br />
    <div class="row">
        <div class="col-md-4">
            <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
                <div class="card-header">Controle sua Casa </div>
                <div class="card-body">
                    <h4 class="card-title">Com o Omega</h4>
                    <p class="card-text">Voce pode controlar sua casa o tempo todo</p>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
                <div class="card-header">Crie Usuarios e de permisoes </div>
                <div class="card-body">
                    <h4 class="card-title">Com o Omega</h4>
                    <p class="card-text">Voce pode criar novos usuarios e dar permisoes especificas para sua casa</p>
                </div>
            </div>
        </div>
    </div>
</div>

CursoIOT/Views/Login/Index.cshtml
@{
    ViewBag.Title = "Login";
}

<h2>Bem Vindo ao Omega</h2>

<<div class="form-group">
    @Html.LabelFor(m => m.nome, new { @class = "col-md-2 control-label" })
    <div class="col-md-10">
        @Html.TextBoxFor(m => m.nome, new { @class = "form-control" })
    </div>
</div>

CursoIOT/Views/Luz/Index.cshtml
@{
    ViewBag.Title = "Projeto Luz";
}
<br />
<h2>Luz</h2>
<br />
<br />

<div class="row">
    <div class="col-md-2">
        <button type="button" class="btn btn-primary" style="background-color:gray">Quarto 1</button>
    </div>
    <div class="col-md-2">
        <button type="button" class="btn btn-primary" style="background-color:gray">Quarto 2</button>
    </div>
    <div class="col-md-2">
        <button type="button" class="btn btn-primary" style="background-color:gray">Cozinha</button>
    </div>
    <div class="col-md-2">
        <button type="button" class="btn btn-primary" style="background-color:gray">Sala</button>
    </div>
    <div class="col-md-2">
        <button type="button" class="btn btn-primary" style="background-color:gray">Luz Externa</button>
    </div>
</div>

CursoIOT/Views/Project/Index.cshtml
@{
    ViewBag.Title = "Project";
}

<br />
<h2>Gerenciador do Projeto</h2>
<br />
<br />


<div class="row">
    <div class="col-md-4">
        <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
            <div class="card-header">Luz</div>
            <div class="card-body">
                @*<h4 class="card-title">Primary card title</h4>*@
                <p class="card-text">ligue e desligue luzes de sua casa.</p>
                <div class="btn-group"><a class="btn btn-info" style="background-color:gray" href="@Url.Action("Index", "Luz")">Ir</a></div>
            </div>
        </div>
        </div>
        <div class="col-md-4">
            <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
                <div class="card-header">Agua</div>
                <div class="card-body">
                    @*<h4 class="card-title">Primary card title</h4>*@
                    <p class="card-text">Feche o registro para evitar desperdicios de agua</p>
                    <button type="button" class="btn btn-primary" style="background-color:gray">Ir</button>
                </div>
            </div>
            </div>

            <div class="col-md-4">
                <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
                    <div class="card-header">temperatura</div>
                    <div class="card-body">
                        @*<h4 class="card-title">Primary card title</h4>*@
                        <p class="card-text">verifique a temperatura da sua casa.</p>
                        <button type="button" class="btn btn-primary" style="background-color:gray">Ir</button>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
                    <div class="card-header">Janelas</div>
                    <div class="card-body">
                        @*<h4 class="card-title">Primary card title</h4>*@
                        <p class="card-text">Abra e feche suas janelas com um click.</p>
                        <button type="button" class="btn btn-primary" style="background-color:gray">Ir</button>
                    </div>
                 </div>
            </div>
            
    </div>

CursoIOT/Views/Shared/_Layout.cshtml
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Omega A casa inteligente</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top " " >
        <a class="navbar-brand" href="#"> Omega</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation" style="">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="@Url.Action("Index", "Home")">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Project")">Project</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("About", "Project")">About</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Login</button>
            </form>
        </div>
    </nav>
</head>

<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

@*<!DOCTYPE html>
    <html>
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Nome do aplicativo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Início", "Index", "Home")</li>
                        <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                        <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
    </html>*@